### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by vincent-gros** [titusz/epubcheck#3] opened 2017-01-11 11:08 UTC
On Windows 8.1, epubcheck can't find any files or folders (including the subfolder samples, or an epub file in the epubcheck folder).

**Comment by titusz** [comment] 2019-08-07 18:52
I cannot reproduce this error. Closing issue. Please reopen if this is still a problem.

**Closed as completed by titusz** 2019-08-07 18:52 UTC
